config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  get 'welcome/index'

  resources :books
  resources :categories
  resources :users, only: [:index, :show, :edit, :update]

    root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  has_many :orderSpecs
  has_many :cart_items
 has_many :carts, :through => :cart_items

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  has_many :books, :through => :cart_items
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :book
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderSpecs
  belongs_to :user
  has_many :books, through: :orderSpecs
end

app/models/order_spec.rb
class OrderSpec < ActiveRecord::Base
  belongs_to :book
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
# has_many :orderSpecs through: :order
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
   @book = Book.find(params[:id])
  end
  def index
      @books = Book.all
    end
  def list
     @books = Book.find(:all)
   end


   def new
#     @book = Book.new
#     @categories = Category.find(:all)
   end
   def create
  #   @book = Book.new(book_params)

  # @book.save
#   redirect_to @book
     @book = Book.new(params[:book])
 if @book.save
       redirect_to :action => 'list'
      else
            @categories = category.find(:all)
           render :action => 'new'
      end
   end
   def update
  @book = Book.find(params[:id])

  if @book.update(article_params)
    redirect_to @book
  else
    render 'edit'
  end
end
   def edit
     @book = Book.find(params[:id])
      @categories = category.find(:all)
   end
   def delete
     Book.find(params[:id]).destroy
     redirect_to :action => 'list'
   end
end
private
  def book_params
    params.require(:book).permit(:name, :category)
  end

app/controllers/cart_controller.rb
class CartController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update] # probably want to keep using this

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # # GET /users/1
  # # GET /users/1.json
  def show

  end

  # GET /users/1/edit
  def edit

  end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:role, :user_name)
    end

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_item_helper.rb
module CartItemHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_spec_helper.rb
module OrderSpecHelper
end

app/helpers/order_specs_helper.rb
module OrderSpecsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/delete.html.erb
<li>
<%= link_to c.title, {:action => 'show', :id => c.id} -%>
<b> <%= link_to 'Edit', {:action => 'edit', :id => c.id} %></b>
<b> <%= link_to "Delete", {:action => 'delete', :id => c.id},
:confirm => "Are you sure you want to delete this item?" %></b>
</li>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for :book, url: book_path(@book), method: :patch do |f| %>

  <% if @books.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_area :category %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if @books.blank? %>
<p>There are not any books currently in the system.</p>
<% else %>
<p>These are the current books in our system</p>
<table>
  <tr>
    <th>Book Name</th>
    <th>Price</th>
    <th>Catergory</th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>

      <td><%= book.category %></td>
    </tr>
  <% end %>
</table>
  <% end %>
<%= link_to 'New book', new_book_path %>

app/views/books/list.html.erb
<% if @books.blank? %>
<p>There are not any books currently in the system.</p>
<% else %>
<p>These are the current books in our system</p>
<ul id="books">
<% @books.each do |c| %>
<li><%= link_to c.title, {:action => "show", :id => c.id} -%>
<b> <%= link_to 'Edit', {:action => "edit",
:id => c.id} %></b></li>
<% end %>
</ul>
<% end %>
<p><%= link_to "Add new Book", {:action => 'new' }%></p>

app/views/books/new.html.erb
<h1>Add new book</h1>
<%= form_for :book, url: books_path do |f| %>  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </p>

 <p>
   <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', books_path %>
<%
=begin %>
<%= form_for :book, url: books_path do |f| %>
<p>
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </p>
  <p>
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </p>
<p>  <%= f.label :category %><br>
  <%= f.text_field :category %>
  </p>

<%= f.submit 'Create' %>
<%= link_to 'Back', books_path %>
<% end %>
<%
=end %>

app/views/books/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>
<%
=begin %>
<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>
<%
=end %>
<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<%= link_to 'Back', books_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>